### ISSUE TITLE
Isuue with Response Status Code

### ISSUE THREAD

**Issue by IvAlex1986** [microsoft/commercial-marketplace-client-dotnet#35]
**Describe the bug**
Please review this line of code: https://github.com/Azure/commercial-marketplace-client-dotnet/blob/main/client/src/Microsoft.Marketplace.SaaS/Generated/FulfillmentOperations.cs#L214
As you can see exception will be thrown only if Status Code is not equal to 200, 400, 403, 404, 500.
So if Response has Status Code 400 than we don't see any information about it.
Is this behavior correct?

**Expected behavior**
If Response has Status Code not equal to 200 than throw exception.

**Comment by msalemcode** [comment]
This issue is addressed with latest code change
