### ISSUE TITLE
FullfillAPI Cannot resolve Subscription Correctly

### ISSUE THREAD

**Issue by GGJason** [microsoft/commercial-marketplace-client-dotnet#54]
**Describe the bug**
The [SubscriptionTerm class](https://github.com/microsoft/commercial-marketplace-client-dotnet/blob/main/src/Microsoft.Marketplace.SaaS/Generated/Models/SubscriptionTerm.cs) not include the property "TermUnit" and the new subscription only provide "termUnit" if I try to call the API directly.
![image](https://user-images.githubusercontent.com/8362482/187355411-cf97f89f-e010-4dd3-a170-7d95952d8530.png)
Because the model was auto-generated by code. Could you please regenerate the code so that I can got the term info for the new subscription?

**To Reproduce**
1. Create new MarketplaceSaaSClient as _marketplaceSaasClient.
2. Call ``` await  _marketplaceSaaSClient.Fulfillment.Resolve(token) ``` to get resolved subscription;
3. try access ``` resolveSubscription.Subscription.Term.TermUnit ``` and you will find that it was not set;

**Expected behavior**
I can access Term.TermUnit as TermUnitEnum type

**Comment by santhoshb-msft** [comment]
Fixed as part of #58
