### ISSUE TITLE
Missing SubscriptionTerm.TermUnit in NuGet version

### ISSUE THREAD

**Issue by MatrixRonny** [microsoft/commercial-marketplace-client-dotnet#61]
**Describe the bug**
The SubscriptionTerm class is missing TermUnit in the NuGet version 1.2.0. The decompiled code looks like this:
``` C#
public class SubscriptionTerm
{
  public DateTimeOffset? StartDate { get; }

  public DateTimeOffset? EndDate { get; }

  internal SubscriptionTerm()
  {
  }

  internal SubscriptionTerm(DateTimeOffset? startDate, DateTimeOffset? endDate)
  {
    StartDate = startDate;
    EndDate = endDate;
  }

  internal static SubscriptionTerm DeserializeSubscriptionTerm(JsonElement element)
  {
    Optional<DateTimeOffset> optional = default(Optional<DateTimeOffset>);
    Optional<DateTimeOffset> optional2 = default(Optional<DateTimeOffset>);
    foreach (JsonProperty item in element.EnumerateObject())
    {
      if (item.NameEquals("startDate"))
      {
        if (item.Value.ValueKind != JsonValueKind.Null)
        {
          JsonElement element2 = item.Value;
          optional = element2.GetDateTimeOffset("O");
        }
      }
      else if (item.NameEquals("endDate") && item.Value.ValueKind != JsonValueKind.Null)
      {
        JsonElement element2 = item.Value;
        optional2 = element2.GetDateTimeOffset("O");
      }
    }

    return new SubscriptionTerm(Optional.ToNullable(optional), Optional.ToNullable(optional2));
  }
}
```

**To Reproduce**
The following code does not compile:
``` C#
IMarketplaceSaaSClient test = null;
var termUnit = (await test.Fulfillment.ResolveAsync(marketPlaceAccessToken)).Value.Subscription.Term.TermUnit;
```

**Expected behavior**
Based on the response from Marketplace Fulfillment API and [SubscriptionTerm](https://github.com/microsoft/commercial-marketplace-client-dotnet/blob/main/src/Microsoft.Marketplace.SaaS/Generated/Models/SubscriptionTerm.cs) class from main branch, the code should compile successfully. I noticed that the property is missing in dev branch.

**Screenshots**
![image](https://github.com/microsoft/commercial-marketplace-client-dotnet/assets/35771215/57c0835c-8a6f-49b5-8b5f-7bc2382e11d0)

**Desktop (please complete the following information):**
 - OS: Windows 10 Business
 - ASP.NET Core project with .NET 6.0
 - Marketplace.SaaS.Client v1.2.0 (NuGet)

**Comment by santhoshb-msft** [comment]
merged latest main in to dev.
