### ISSUE TITLE
What is `TermUnitEnum`? I cannot see no documentation or explanations

### ISSUE THREAD

**Issue by xperiandri** [microsoft/commercial-marketplace-client-dotnet#69]
**Describe the bug**
[`src/Microsoft.Marketplace.SaaS/Generated/Models/TermUnitEnum.cs` ](https://github.com/microsoft/commercial-marketplace-client-dotnet/blob/main/src/Microsoft.Marketplace.SaaS/Generated/Models/TermUnitEnum.cs) is not well described.

**Expected behavior**
The summary of the enum explains what it is about and how to use it.
Each case has a description

 - Version 1.2

**Comment by xperiandri** [comment]
@scseely

**Comment by santhoshb-msft** [comment]
@xperiandri the TermUnit is from the subscription payload which is described here https://learn.microsoft.com/en-us/partner-center/marketplace/partner-center-portal/pc-saas-fulfillment-subscription-api#post-httpsmarketplaceapimicrosoftcomapisaassubscriptionsresolveapi-versionapiversion.

Please let me know if this helps

**Comment by santhoshb-msft** [comment]
@xperiandri I hope the above answers your questions. Please feel free to reopen on any follow up questions. Closing this for now.
